//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS201724112142.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public string Eid { get; set; }
        public string Ename { get; set; }
        public string Esize { get; set; }
        public string Epic { get; set; }
        public Nullable<double> Eprice { get; set; }
        public Nullable<System.DateTime> Edate { get; set; }
        public string Eplace { get; set; }
        public string manager { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
